name: bilibili box
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "12 3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GIST_token }}
          GIST_ID: 67c5df77fc9ee0ad0b48d9bd781d7eaa
          UID: "351534170"
        run: git clone https://github.com/KeJunMao/bilibili-box.git && cd bilibili-box && deno run --allow-net --allow-env index.ts
